spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testb?autoReconnect=true&useSSL=true&serverTimezone=UTC
    username: user
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 256374489305-hglea37snvg8quu8dda74uiu1q77qb3j.apps.googleusercontent.com
            clientSecret: 52lDPRZtaxdGZlSqaj6G8on4
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 429668214310991
            clientSecret: 1f0f4aff012d4e96d7706f3f79e7cd9f
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile

management:
  endpoint:
    beans:
      enabled: true