spring:
  datasource:
    url: jdbc:mysql://localhost:3306/budget?autoReconnect=true&useSSL=true
    username: user
    password: user
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect