spring:
  datasource:
    url: jdbc:mysql://localhost:3306/budget?autoReconnect=true&useSSL=true&serverTimezone=UTC
    username: user
    password: user
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect